#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules
module load eb
module load Miniconda2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
source activate qiime1

#Pick OTUs
echo "Picking OTUs"
pick_closed_reference_otus.py -i ~/1/2018_02_smb/SeqPrep_joined/slout_q20/seqs.fna -o ~/1/2018_02_smb/SeqPrep_joined/slout_q20/picked_otus_default -a -O 24

source deactivate
