#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# summarise table
echo "summarise biom table"
biom summarize-table -i ~/1/2018_02_smb/SeqPrep_joined/slout_q20/picked_otus_default/otu_table.biom -o ~/1/2018_02_smb/SeqPrep_joined/slout_q20/picked_otus_default/otu_table_summary.txt

source deactivate
