#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules
module load eb
module load Miniconda2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
source activate qiime1

# alpha diversity analysis
echo "alpha diversity analysis"
time alpha_diversity.py -i otu_table_mc2_w_tax_no_pynast_failures.biom -m observed_otus,shannon,chao1,simpson,PD_whole_tree -o adiv_values_all.txt -t rep_set.tre

source deactivate
