#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules
module load eb
module load Miniconda2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
source activate qiime1

# core diversity analysis
echo "core diversity analysis"
time core_diversity_analyses.py -i ~/1/2018_02_smb/SeqPrep_joined/slout_q20/ucrss2/otu_table_mc2_w_tax.biom -o ~/1/2018_02_smb/SeqPrep_joined/slout_q20/ucrss2/core_output -m ~/1/2018_02_smb/map.tsv  -t ~/1/2018_02_smb/SeqPrep_joined/slout_q20/ucrss2/rep_set.tre -e 748

source deactivate
