#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# summarise table
echo "summarise biom table"
time biom summarize-table -i ~/1/2018_02_smb/SeqPrep_joined/slout_q20/ucrss2/otu_table_mc2_w_tax_no_pynast_failures.biom -o ~/1/2018_02_smb/SeqPrep_joined/slout_q20/ucrss2/otu_table_summary2.txt

source deactivate
